# Dockerfile_code

FROM python:3.10-slim

RUN pip install \
    dagster \
    dagster-postgres \
    dagster-docker \
    dagster-dbt \
    dbt-core \
    dbt-athena-community

# Set $DAGSTER_HOME and copy dagster instance there
ENV DAGSTER_HOME=/opt/dagster/dagster_home/
ENV PYTHONPATH=/opt/dagster/app/orchestration

RUN mkdir -p $DAGSTER_HOME

# Add repository code
WORKDIR /opt/dagster/app

COPY . /opt/dagster/app

# Run dagster gRPC server on port 4000
EXPOSE 4000

# CMD allows this to be overridden from run launchers or executors that want
# to run other commands against your repository
CMD ["dagster", "api", "grpc", "-h", "0.0.0.0", "-p", "4000", "-f", "orchestration/orchestration/definitions.py"]
