athena_dbt_core:
  target: dev
  outputs:
    dev:
      aws_profile: default
      type: athena
      s3_staging_dir: s3://iceberg-data-bucket/staging/
      s3_data_dir: s3://iceberg-data-bucket/data/
      region_name: eu-west-1
      schema: dbt_database
      database: awsdatacatalog
      work_group: primary
