
services:
  docker_postgresql:
    image: postgres:11
    container_name: docker_postgresql
    environment:
      POSTGRES_USER: "postgres_user"
      POSTGRES_PASSWORD: "postgres_password"
      POSTGRES_DB: "postgres_db"
    networks:
      - docker_network

  dagster_webserver:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    entrypoint:
      - dagster-webserver
      - -h
      - "0.0.0.0"
      - -p
      - "3000"
      - -w
      - workspace.yaml
    container_name: dagster_webserver
    expose:
      - "3000"
    ports:
      - "3000:3000"
    environment:
      DB_USERNAME: "postgres_user"
      DB_PASSWORD: "postgres_password"
      DB_NAME: "postgres_db"
      DB_PORT: 5432
      DB_HOST: "docker_postgresql"
    volumes: # Make docker client accessible so we can launch containers using host docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
    networks:
      - docker_network
    depends_on:
      - docker_postgresql
      - dagster_user_code
    
  dagster_daemon:
    build:
      context: .
      dockerfile: ./Dockerfile_dagster
    entrypoint:
      - dagster-daemon
      - run
    container_name: dagster_daemon
    image: dagster_image
    restart: on-failure
    environment:
      DB_USERNAME: "postgres_user"
      DB_PASSWORD: "postgres_password"
      DB_NAME: "postgres_db"
      DB_PORT: 5432
      DB_HOST: "docker_postgresql"
      DAGSTER_INSTANCE_IMAGE: dagster_image
    volumes: # Make docker client accessible so we can launch containers using host docker
      - /var/run/docker.sock:/var/run/docker.sock
      - /tmp/io_manager_storage:/tmp/io_manager_storage
      - ~/.aws:/root/.aws
    networks:
      - docker_network
    depends_on:
      - docker_postgresql
      - dagster_user_code

  dagster_user_code:
    build:
      context: ../
      dockerfile: orchestration/Dockerfile_code
    container_name: dagster_user_code
    image: dagster_user_code_image
    restart: always
    expose:
      - "4000"
    environment:
      DB_USERNAME: "postgres_user"
      DB_PASSWORD: "postgres_password"
      DB_NAME: "postgres_db"
      DB_PORT: 5432
      DB_HOST: "docker_postgresql"
      DAGSTER_CURRENT_IMAGE: "dagster_user_code_image"
    networks:
      - docker_network
    depends_on:
      - docker_postgresql


networks:
  docker_network:
    driver: bridge
    name: docker_network