version: 2

models:
  - name: stg_client
    description: "Staging table for client data"
    columns:
      - name: client_id
        description: "The primary key for this table"
        data_tests:
          - not_null
      - name: client_name
        description: "The name of the client"
      - name: join_date
        description: "The date the client joined"
        data_tests:
          - not_null

  - name: stg_product
    description: "Staging table for product data"
    columns:
      - name: product_id
        description: "The primary key for this table"
        data_tests:
          - not_null
      - name: product_name
        description: "The name of the product"
      - name: client_id
        description: "Foreign key linking to client"
      - name: product_date
        description: "The date of the product"
      - name: price
        description: "The price of the product"
        data_tests:
          - not_null
